import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true
});

test('test', async ({ page }) => {
  await page.goto('https://icmsdev-cas.kra.go.ke:36091/cas/login?service=https%3A%2F%2Ficmsdev-app01.kra.go.ke%3A36081%2Fwelcome.jsp');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.locator('#loginBtn').click();
  await page.locator('#demoCLR').click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').fill('25WILIM000000011');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('listitem', { name: 'Logout' }).dblclick();
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.locator('#loginBtn').click();
  await page.locator('#demoCLR').click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').press('ControlOrMeta+V');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').fill('25WILIM000000011');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Assess' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537236565"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537236565"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('link', { name: 'Close' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Assess' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('logisticsllc@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('kay');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).dblclick();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('07049798');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByText('07049798').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByText('07049798').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByText('07049798').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('foreignllc@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('1326859');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537365112"]').contentFrame().getByText('1326859').click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('link', { name: 'Close' }).click();
  await page.getByRole('listitem', { name: 'Logout' }).click();
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.locator('#loginBtn').click();
  await page.locator('#demoCLR').click();
  await page.getByText('Declaration Search Capture').click();
  await page.locator('#msg10135').click();
  await page.locator('#msg10135').click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').fill('25WILIM000000011');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('listitem', { name: 'Logout' }).dblclick();
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.locator('#loginBtn').click();
  await page.locator('#demoCLR').click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').press('ControlOrMeta+V');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="reg_num"]').fill('25WILIM000000011');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Assess' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('L');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#IDFMail').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('row', { name: 'L', exact: true }).getByRole('textbox').fill('Logisticsllc@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row1cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('kayl');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('0701200');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('foreign@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('willis');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('106659');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('textbox').nth(5).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('textbox').nth(5).fill('US');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row7cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row8cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row9cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row9cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('90 days');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('INV003');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row11cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row11cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#csDate_field_aasss').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('link', { name: '10' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('button', { name: 'Done' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('sportman');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row13cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('cigarette');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763537833650"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('link', { name: 'Close' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Assess' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('logisticsllc@gmail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row1cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row1cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('07022841268');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('row', { name: '07022841268', exact: true }).getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('row', { name: '07022841268', exact: true }).getByRole('textbox').fill('mayl');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('0701006029');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('foreighn@gmail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('kayl');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('105666');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('textbox').nth(5).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('textbox').nth(5).fill('US');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row7cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row8cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row9cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row9cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('90 days');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('INV003');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row11cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row11cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#csDate_field_aasss').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('link', { name: '10' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('button', { name: 'Done' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('sportman');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row13cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row13cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('cigarettes');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').press('NumLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').press('Clear');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').press('NumLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('5');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row15cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row15cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('sportman manufacturer');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row16cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row16cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row16cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row16cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('textbox').nth(5).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByText('Bag', { exact: true }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row17cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row17cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#DCLGr1PackingType > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('span').filter({ hasText: '2' }).nth(1).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row18cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row18cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('20');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row19cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row19cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row19cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('5');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row20cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row20cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('20');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row21cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row21cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('plain');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('#row22cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('row', { name: '1 24022010 IDFCondition Goods condition', exact: true }).getByRole('checkbox').check();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('row', { name: '1 24022010 IDFCondition IDFCondition Goods condition', exact: true }).getByRole('checkbox').check();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().getByRole('button', { name: 'Declare' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('.icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('input[name="serial_num"]').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('input[name="serial_num"]').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('input[name="serial_num"]').fill('INV');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('input[name="serial_num"]').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().locator('input[name="serial_num"]').fill('INV003');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763538196959"]').contentFrame().locator('iframe[name="fancybox-frame1763538511803"]').contentFrame().getByRole('button', { name: 'Declare' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('25WILIM000000011').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Register' }).click();
  await page.getByRole('button', { name: 'register' }).click();
});