import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true
});

test('test', async ({ page }) => {
  await page.goto('https://icmsdev-cas.kra.go.ke:36091/cas/login?service=https%3A%2F%2Ficmsdev-app01.kra.go.ke%3A36081%2Fwelcome.jsp');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.locator('#loginBtn').click();
  await page.getByRole('button', { name: 'Force login' }).click();
  await page.locator('#demoCLR').click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b1_decla_sub1"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Import Declaration Form').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="boxa_office_code"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('LTK').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="boxa_office_sub_code"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('LOITOKITOK').click();
  await page.getByRole('link', { name: 'X' }).click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b1_decla_sub1"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Import Declaration Form').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('textbox').nth(2).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('MYD').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="boxa_office_sub_code"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('div').filter({ hasText: 'Code Desc MLDMALINDI' }).first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="boxa_office_sub_code"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.error').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.error').click();
  await page.locator('iframe').nth(1).contentFrame().locator('div').filter({ hasText: 'Code Desc MLDMALINDI' }).first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.error').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('MALINDI').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').dblclick();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').press('ControlOrMeta+c');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').fill('P000600883U');
  await page.locator('iframe').nth(1).contentFrame().locator('#Con7754').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub1"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Cost, insurance and freigh..').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').fill('MLD');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').fill('2000');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').check();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').uncheck();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').fill('mary killy');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('984\n');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('984\nUSA');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').fill('US');
  await page.locator('iframe').nth(1).contentFrame().getByRole('cell', { name: '2. Consignor / exporter - Registered - Registration Number - Name mary killy - Address 984 USA - Nationality US United States Email Country code US 16. Date of Exit/Arrival 23. Exchange rate D.Seals Number Seal Activation D. CD acceptance date and time D. CD acceptance officer Transfer funds flag Transfer funds CD registration number Rotation Number Rotation validation date/time', exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Movements').first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b25_border_trans"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Air transport').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Attachments').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('link').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('#List9023 > .w-field.w-field-mandatory.ui_list_ListOfValue_text').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('General', { exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#List9024 > .w-field.w-field-mandatory.ui_list_ListOfValue_text').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('205').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="serial_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="serial_num"]').fill('INV004');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="serial_num"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Save' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#Field8462').getByRole('radio').check();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Tariff Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().locator('div').filter({ hasText: 'Matching HS code Matching HS' }).nth(4).click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().locator('input[name="hsCode"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().locator('input[name="hsCode"]').fill('24022010');
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().getByText('24022010').click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542147392"]').contentFrame().getByRole('button', { name: 'Use HS code' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('cell', { name: '33. Commodity code Commodity HS code 24022010 Submit Tariff Search Additional code 1 Additional code 2 Additional code 3 31. Commercial description of the goods Tariff description of the good', exact: true }).click();
  await page.goto('https://icmsdev-app01.kra.go.ke:36081/e-biscus/dispatchAction.action?service=CR&menuReload=true#');
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'X' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.goto('https://icmsdev-app01.kra.go.ke:36081/e-biscus/dispatchAction.action?service=CR&menuReload=true#');
  await page.getByText('Declaration Search Capture').click();
  await page.locator('#msg12135').click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b33_commodity_code"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Tariff Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542439756"]').contentFrame().locator('input[name="hsCode"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542439756"]').contentFrame().locator('input[name="hsCode"]').fill('24022010');
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542439756"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542439756"]').contentFrame().getByText('24022010').click();
  await page.locator('iframe').nth(1).contentFrame().locator('iframe[name="fancybox-frame1763542439756"]').contentFrame().getByRole('button', { name: 'Use HS code' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#Con7754').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b34_origin_country"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b34_origin_country"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b34_origin_country"]').fill('US');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b42_item_price"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b42_item_price"]').fill('2000');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b38_net_mass"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b38_net_mass"]').fill('100');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b41_unit_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b41_unit_num"]').fill('100');
  await page.locator('iframe').nth(1).contentFrame().getByText('Procedure').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Attachments').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('link').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('cell').filter({ hasText: /^$/ }).nth(2).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#List9030 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('General', { exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('row', { name: 'A General', exact: true }).locator('input[name="reference"]').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('205').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="serial_num"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="serial_num"]').fill('INV004');
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Save' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#Field10996').getByRole('radio').check();
  await page.goto('https://icmsdev-app01.kra.go.ke:36081/e-biscus/dispatchAction.action?service=CR&menuReload=true#');
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('P000600883U').nth(1).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.getByRole('link', { name: 'X' }).nth(1).click();
  await page.getByRole('link', { name: 'X' }).click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.getByRole('link', { name: 'X' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByText('P000600883U').nth(3).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#row1cell8Col9351 > .refdiv').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Process' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'DV1' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('#FDV1InvDate_field_aasss').click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('link', { name: '10' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('input[name="DV1InvNum"]').click();
  await page.locator('iframe').nth(2).contentFrame().locator('input[name="DV1InvNum"]').fill('INV004');
  await page.locator('iframe').nth(2).contentFrame().locator('input[name="DV1InvNum"]').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('#FDV1BuySellRel > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(2).contentFrame().getByText('Not related').click();
  await page.locator('iframe').nth(2).contentFrame().locator('input[name="DV1NetPrice"]').click();
  await page.locator('iframe').nth(2).contentFrame().locator('input[name="DV1NetPrice"]').fill('2000');
  await page.locator('iframe').nth(2).contentFrame().locator('html').click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Save' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Assess' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('logistics@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row1cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row1cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('killy');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row2cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('076998');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row3cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#IDFMail').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#IDFMail').getByRole('textbox').fill('foreign@mail.com');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row4cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('milly');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row5cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldStringPhoneFax').getByRole('textbox').fill('198985');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row6cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('textbox').nth(5).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('textbox').nth(5).fill('US');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row7cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row9cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('90 days');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row10cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('INV004');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').press('CapsLock');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row11cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#csDate_field_aasss').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('link', { name: '10' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('button', { name: 'Done' }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row12cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('sportman');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row13cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('cigarette');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row14cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('5');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row15cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row15cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString80').getByRole('textbox').fill('sportman manufacturer');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row16cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('.icon-exclamatory').first().click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#DCLGr3PackagingMode > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByText('Bag', { exact: true }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row17cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row17cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row17cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('div').filter({ hasText: /^22$/ }).click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row18cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row18cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('20');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row19cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row19cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('5');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row20cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row20cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#CF7612').getByRole('textbox').fill('20');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row21cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row21cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#FieldString35').getByRole('textbox').fill('plain');
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().locator('#row22cell6cpldvCol > .icon-exclamatory').click();
  await page.locator('iframe').nth(2).contentFrame().locator('iframe[name="fancybox-frame1763542760048"]').contentFrame().getByRole('button', { name: 'Declare' }).click();
  await page.locator('iframe').nth(2).contentFrame().getByRole('button', { name: 'Register' }).click();
  await page.getByRole('button', { name: 'register' }).click();
});