import { test, expect } from '@playwright/test';

test.use({
  ignoreHTTPSErrors: true
});

test('test', async ({ page }) => {
  await page.goto('https://icmsdev-cas.kra.go.ke:36091/cas/login?service=https%3A%2F%2Ficmsdev-app01.kra.go.ke%3A36081%2Fwelcome.jsp');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('CSAP000600883UG');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password' }).fill('KEN12345');
  await page.getByRole('textbox', { name: 'Password' }).press('CapsLock');
  await page.locator('#loginBtn').click();
  await page.getByRole('button', { name: 'Force login' }).click();
  await page.locator('#demoCLR').click();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1087 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Import Declaration Form').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByText('BUS', { exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1090 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.focus').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.focus').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.focus').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.error').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('BUSIA').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').dblclick();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').press('ControlOrMeta+c');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').fill('P000600883U');
  await page.locator('iframe').nth(1).contentFrame().locator('#rightDetail td').filter({ hasText: 'Undefined message 2.' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').check();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').uncheck();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').fill('tyla');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('767\n');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('767\nUSA');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').fill('US');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1099 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('CIF', { exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').fill('BSA');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').fill('3000');
  await page.locator('iframe').nth(1).contentFrame().getByText('Movements').first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.focus').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Air transport').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Attachments').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Details').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Save' }).click();
  await page.goto('https://icmsdev-app01.kra.go.ke:36081/e-biscus/dispatchAction.action?service=CR&menuReload=true#');
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Capture' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').dblclick();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b14_declarant_tr"]').press('ControlOrMeta+c');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b8_consignee_tr"]').fill('P000600883U');
  await page.locator('iframe').nth(1).contentFrame().locator('#rightDetail td').filter({ hasText: 'Undefined message 2.' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1087 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Import Declaration Form').click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button').first().click();
  await page.locator('iframe').nth(1).contentFrame().getByText('BDO').click();
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1090 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('BONDO').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').check();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_registered"]').uncheck();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_name"]').fill('killy');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('7889\n');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').fill('7889\nUSA');
  await page.locator('iframe').nth(1).contentFrame().locator('textarea[name="b2_address"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b2_country"]').fill('US');
  await page.locator('iframe').nth(1).contentFrame().locator('#sclist1099 > .ui_list_ListOfValue_button').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('CIF', { exact: true }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').fill('BDO');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b20_deliv_terms_sub2"]').press('CapsLock');
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').click();
  await page.locator('iframe').nth(1).contentFrame().locator('input[name="b22_total_amount"]').fill('2500');
  await page.locator('iframe').nth(1).contentFrame().getByText('Movements').first().click();
  await page.locator('iframe').nth(1).contentFrame().locator('.ui_list_ListOfValue_button.mandatory.focus').click();
  await page.locator('iframe').nth(1).contentFrame().getByText('Air transport').click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Save' }).click();
  await page.locator('iframe').nth(1).contentFrame().locator('#Field8462').getByRole('radio').check();
  await page.locator('iframe').nth(1).contentFrame().locator('#Field10996').getByRole('radio').check();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('link', { name: '[25BDOIM000000273-1]' }).dblclick();
  await page.getByRole('link', { name: 'Declaration' }).click();
  await page.getByRole('link', { name: 'Search' }).click();
  await page.locator('iframe').nth(1).contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.getByRole('link', { name: 'X' }).click();
});